name: nf_test
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.15
  - biopython=1.78
  - pandas=1.1.5
  - seaborn=0.11.2
  - matplotlib=3.3.4
  - bcftools=1.15.1
  - samtools=1.15.1
  - ete3=3.1.2
  ## NOTE iqtree2 and ete-toolkit (part of the ete3 install) may not be cross compatible. ete-toolkit automatically downgrades to iqtree v. 1.5?
  - iqtree=2.2.0.3

## I personally solved the iqtree2 and ete3 incompatibility by creating two conda environments:
## 1. For all bioinformatic/phylogenetic analyses (conda env titled: nf_phylo)
## 2. For running ete3 and visualization in python specifically (conda env titled: ete3)